[triage_dashboard]
display.general.type = views
display.page.show.chrome = 1
display.page.search.showFields = 0

[alert_detail]
display.general.type = views
display.page.show.chrome = 1
display.page.search.showFields = 0

[analyst_metrics]
display.general.type = views
display.page.show.chrome = 1

[suppression]
display.general.type = views
display.page.show.chrome = 1
